	
@url = http://localhost:3000

GET {{url}}/tarefas

###

# Buscando tarefas por Query String (Filtro)
GET {{url}}/tarefas?busca=estudar

###

POST {{url}}/tarefas
Content-Type: application/json

{
    "id": 4,
    "descricao": "Tarefa 4",
    "concluido": false
}

###

GET {{url}}/tarefas/1

###

PUT {{url}}/tarefas/1
Content-Type: application/json

{
    "descricao": "Fazer compras no mercado",
    "concluido": true
}

###

DELETE {{url}}/tarefas/1

###

# Forçando erro 404 no NotFoundHandler
GET {{url}}/batata-frita